---
mcc: '001'          # Mobile Country Code value
mnc: '01'           # Mobile Network Code value (2 or 3 digits)

nci: '0x000000010'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 1              # Tracking Area Code

# gNB's local IP address for Radio Link Simulation
linkIp: 192.168.28.100
# gNB's local IP address for N2 Interface
ngapIp: 192.168.29.65
# gNB's local IP address for N3 Interface
gtpIp: 192.168.29.65

# List of AMF address information
amfConfigs:
  - address: 192.168.26.60
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1
    sd: 000000

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
