version: '2'
services:
  tomcat:
    image: vulhub/tomcat:8.0
    build:
     context: .
    hostname: "${CONTAINER_NAME}"
    security_opt:
     - apparmor:erichough-nfs
    cap_add:
     - SYS_ADMIN
    volumes:
     - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
     - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
     - ./context.xml:/usr/local/tomcat/webapps/host-manager/META-INF/context.xml
    networks: [servers]
    labels:
     - "dovesnap.faucet.mirror=true"
networks:
  servers:
    external:
      name: servers
