acls:
  protectcpn:
    rules:
    - rule:
      eth_type: 0x806
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ip_proto: 132
      ipv4_src: 192.168.0.0/16
      ipv4_dst: 192.168.26.20
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ip_proto: 17
      ipv4_src: 192.168.0.0/16
      ipv4_dst: 192.168.26.30
      udp_src: 8805
      udp_dst: 8805
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ip_proto: 17
      ipv4_src: 192.168.0.0/16
      ipv4_dst: 192.168.26.40
      udp_src: 8805
      udp_dst: 8805
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ip_proto: 6
      ipv4_dst: 192.168.26.6
      tcp_dst: 3000
      actions:
        allow: 1
    - rule:
      actions:
        allow: 0
  protectupn:
    rules:
    - rule:
      eth_type: 0x806
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ip_proto: 132
      ipv4_src: 192.168.26.0/24
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ip_proto: 17
      ipv4_src: 192.168.29.0/24
      udp_src: 2152
      udp_dst: 2152
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ip_proto: 17
      ipv4_src: 192.168.27.1
      udp_src: 2152
      udp_dst: 2152
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ip_proto: 17
      ipv4_src: 192.168.29.0/24
      udp_src: 8805
      udp_dst: 8805
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ip_proto: 17
      ipv4_src: 192.168.26.0/24
      udp_src: 8805
      udp_dst: 8805
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ipv4_src: 192.168.0.0/16
      actions:
        allow: 0
    - rule:
      eth_type: 0x800
      ip_proto: 17
      udp_dst: 8805
      actions:
        allow: 0
    - rule:
      eth_type: 0x800
      ip_proto: 17
      udp_dst: 2152
      actions:
        allow: 0
    - rule:
      eth_type: 0x800
      ip_proto: 132
      actions:
        allow: 0
    - rule:
      eth_type: 0x800
      ipv4_dst: 192.168.27.41
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ipv4_dst: 192.168.27.42
      actions:
        allow: 1
    - rule:
      actions:
        allow: 0
  protectenb:
    rules:
    - rule:
      eth_type: 0x806
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ip_proto: 132
      ipv4_src: 192.168.26.0/24
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ip_proto: 17
      udp_src: 8805
      udp_dst: 8805
      actions:
        allow: 1
    - rule:
      eth_type: 0x800
      ip_proto: 17
      udp_src: 2152
      udp_dst: 2152
      actions:
        allow: 1
    - rule:
      actions:
        allow: 0
  protectrfn:
    rules:
    - rule:
      actions:
        allow: 0
