---
logger:
  file: /usr/local/var/log/open5gs/mme.log
  trace:
    app: 1
    s1ap: 1
    nas: 1
    diameter: 1
    gtpv2: 1

mme:
  freeDiameter: /usr/local/etc/freeDiameter/mme.conf
  s1ap:
    addr: 192.168.26.20
  gtpc:
    addr: 192.168.26.20
  gummei:
    plmn_id:
      mcc: 001
      mnc: 01
    mme_gid: 2
    mme_code: 1
  tai:
    plmn_id:
      mcc: 001
      mnc: 01
    tac: 1
  security:
    integrity_order: [EIA1, EIA2, EIA0]
    ciphering_order: [EEA0, EEA1, EEA2]
  network_name:
    full: Open5GS

sgwc:
  gtpc:
    addr: 192.168.26.30

smf:
  gtpc:
    - addr: 192.168.26.40
