### For reference, see `nextepc.conf`

logger:
  file: /usr/local/var/log/open5gs/upf2.log
  trace:
      app: 1
      diameter: 1
      gtpv2: 1
      gtp: 1

upf:
  gtpu:
    addr:
      - 192.168.27.42
  pfcp:
    - addr: 192.168.27.42
  subnet:
    - addr: 10.11.0.1/16
      apn: internet2
      dev: ogstap
    - addr: 10.12.0.1/16
      apn: internet3
      dev: ogstap2
