# using version 2 for the gateway option with ipam
version: '2'

networks:
  rfn:
    external:
      name: rfn
  ran:
    external:
      name: ran
services:
  gnb:
    image: iqtlabs/ueransim:v0.8.0
    container_name: gnb
    depends_on:
      nrf:
        condition: service_healthy
      mme:
        condition: service_started
    cap_add:
      - SYS_NICE
      - NET_ADMIN
    networks:
      ran:
        ipv4_address: 192.168.29.65
      rfn:
        ipv4_address: 192.168.28.100
    volumes:
      - "../configs/UERANSIM:/config:z"
    labels:
      - "daedalus.namespace=primary"
    entrypoint:
      - /scripts/run_rfn_gnb.sh
    command:
      - -c
      - /config/gnb.yaml
