FROM iqtlabs/srsran-base:latest
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"
ARG SRS_VERSION=release_21_10
WORKDIR /root
RUN git clone https://github.com/srsRAN/srsRAN.git -b ${SRS_VERSION} \
    && mkdir -p /root/srsRAN/build \
    && cd /root/srsRAN/build \
    && cmake -DENABLE_AVX512=OFF ../ && make -j `nproc` && make install && ldconfig
WORKDIR /root
RUN mkdir /config
