# using version 2 for the gateway optiono with ipam
version: '2'

networks:
  upn:
    external:
      name: upn
  rfn:
    external:
      name: rfn
services:
  enb:
    image: srslte:latest
    container_name: enb
    depends_on:
      - mme
    cap_add:
      - SYS_NICE
    networks:
      upn:
        ipv4_address: 192.168.27.60
      rfn:
        ipv4_address: 192.168.28.60
    volumes:
      - ./config_upn/srsLTE:/config:z
    entrypoint:
      - srsenb
    command:
      - /config/enb.conf
      - --enb.name=dummyENB01
      - --enb.mcc=001
      - --enb.mnc=01
      - --enb.enb_id=0x60
      - --enb.mme_addr=192.168.26.20
      - --enb.gtp_bind_addr=192.168.27.60
      - --enb.s1c_bind_addr=192.168.27.60
      - --enb_files.rr_config=/config/rr.conf
      - --enb_files.sib_config=/config/sib.conf
      - --enb_files.drb_config=/config/drb.conf
