# using version 2 for the gateway optiono with ipam
version: '2'

volumes:
 mongodb_data:

networks:
  core_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: core
      com.docker.network.driver.mtu: 9000
    ipam:
      driver: default
      config:
	- subnet: 192.168.26.0/24
	  gateway: 192.168.26.1
  rf_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: rf
      com.docker.network.driver.mtu: 9000
    ipam:
      driver: default
      config:
	- subnet: 192.168.28.0/24
	  gateway: 192.168.28.1

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${DB_USER}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}'
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb
    networks:
      core_network:
        ipv4_address: 192.168.26.5

  webui:
    image: open5gs:latest
    depends_on:
      - mongodb
    environment:
      - 'DB_URI=mongodb://${DB_USER}:${DB_PASS}@mongodb/open5gs?authSource=admin'
      - DB_HOST=mongodb
    container_name: webui
    hostname: webui
    ports:
      - "3000:3000"
    volumes:
      - "./config:/usr/local/etc:z"
    command:
      - "/usr/local/etc/run_webui.sh"
    networks:
      core_network:
        ipv4_address: 192.168.26.6

  mongodbloader:
    image: mongo:latest
    depends_on:
      - webui
    environment:
      - DB_HOST=mongodb
      - 'DB_USER=${DB_USER}'
      - 'DB_PASS=${DB_PASS}'
    volumes:
      - "./provisioning/db/run_db.sh:/tmp/run.sh:z"
      - "./provisioning/db/imsi1.json:/tmp/imsi1.json:z"
    entrypoint:
      - /bin/sh
      - /tmp/run.sh
    networks:
      core_network:
	ipv4_address: 192.168.26.19

  hss:
    image: open5gs:latest
    depends_on:
      - mongodb
    container_name: hss
    hostname: hss
    environment:
      - DB_HOST=mongodb
      - 'DB_USER=${DB_USER}'
      - 'DB_PASS=${DB_PASS}'
    command:
      - "/usr/local/etc/run_hss.sh"
    volumes:
      - "./config:/usr/local/etc:z"
    networks:
      core_network:
	ipv4_address: 192.168.26.10

  pcrf:
    image: open5gs:latest
    depends_on:
      - mongodb
      - hss
    container_name: pcrf
    hostname: pcrf
    environment:
      - DB_HOST=mongodb
      - 'DB_USER=${DB_USER}'
      - 'DB_PASS=${DB_PASS}'
    command:
      - "/usr/local/etc/run_pcrf.sh"
    volumes:
      - "./config:/usr/local/etc:z"
    networks:
      core_network:
	ipv4_address: 192.168.26.50

  mme:
    image: open5gs:latest
    depends_on:
      - hss
    container_name: mme
    hostname: mme
    command:
      - "/usr/local/etc/run_mme.sh"
    volumes:
      - "./config:/usr/local/etc:z"
    networks:
      core_network:
	ipv4_address: 192.168.26.20

  smf:
    image: open5gs:latest
    container_name: smf
    hostname: smf
    command:
      - "/usr/local/etc/run_smf.sh"
    volumes:
      - "./config:/usr/local/etc:z"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      core_network:
	ipv4_address: 192.168.26.40

  sgwc:
    image: open5gs:latest
    container_name: sgwc
    hostname: sgwc
    command:
      - "/usr/local/etc/run_sgwc.sh"
    volumes:
      - "./config:/usr/local/etc:z"
    networks:
      core_network:
	ipv4_address: 192.168.26.30

  sgwu:
    image: open5gs:latest
    container_name: sgwu
    hostname: sgwu
    command:
      - "/usr/local/etc/run_sgwu.sh"
    volumes:
      - "./config:/usr/local/etc:z"
    networks:
      core_network:
	ipv4_address: 192.168.26.31

  sgwu2:
    image: open5gs:latest
    container_name: sgwu2
    hostname: sgwu2
    command:
      - "/usr/local/etc/run_sgwu2.sh"
    volumes:
      - "./config:/usr/local/etc:z"
    networks:
      core_network:
	ipv4_address: 192.168.26.32

  upf:
    image: open5gs:latest
    container_name: upf
    hostname: upf
    command:
      - "/usr/local/etc/run_upf.sh"
    volumes:
      - "./config:/usr/local/etc:z"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      core_network:
	ipv4_address: 192.168.26.41

  upf2:
    image: open5gs:latest
    container_name: upf2
    hostname: upf2
    command:
      - "/usr/local/etc/run_upf2.sh"
    volumes:
      - "./config:/usr/local/etc:z"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      core_network:
	ipv4_address: 192.168.26.42

  enb:
    image: srslte:latest
    container_name: enb
    depends_on:
      - mme
    cap_add:
      - SYS_NICE
    networks:
      core_network:
	ipv4_address: 192.168.26.60
      rf_network:
	ipv4_address: 192.168.28.60
    volumes:
      - ./config/srsLTE:/config:z
    entrypoint:
      - srsenb
    command:
      - /config/enb.conf
      - --enb.name=dummyENB01
      - --enb.mcc=001
      - --enb.mnc=01
      - --enb.enb_id=0x18AF1
      - --enb.mme_addr=192.168.26.20
      - --enb.gtp_bind_addr=192.168.26.60
      - --enb.s1c_bind_addr=192.168.26.60
      - --enb_files.rr_config=/config/rr.conf
      - --enb_files.sib_config=/config/sib.conf
      - --enb_files.drb_config=/config/drb.conf
  ue:
    image: srslte:latest
    container_name: ue
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    networks:
      rf_network:
        ipv4_address: 192.168.28.61
    depends_on:
      - enb
    volumes:
      - ./config/srsLTE:/config:z
    entrypoint:
      - srsue
    command:
      - /config/ue.conf
      - --usim.imsi=001010000000001
      - --usim.k=c8eba87c1074edd06885cb0486718341
      - --usim.algo=milenage
      - --usim.opc=17b6c0157895bcaa1efc1cef55033f5f
      - --nas.apn=internet
      - --rf.dl_earfcn=2850
      - --rf.device_args="tx_port=tcp://*:5554,rx_port=tcp://192.168.28.60:5555,id=ue,base_srate=1.92e6"
  ue2:
    image: srslte:latest
    container_name: ue2
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    networks:
      rf_network:
        ipv4_address: 192.168.28.62
    depends_on:
      - enb
    volumes:
      - ./config/srsLTE:/config:z
    entrypoint:
      - srsue
    command:
      - /config/ue.conf
      - --usim.imsi=001010000000002
      - --usim.k=c8eba87c1074edd06885cb0486718341
      - --usim.algo=milenage
      - --usim.opc=17b6c0157895bcaa1efc1cef55033f5f
      - --nas.apn=internet2
      - --rf.dl_earfcn=3050
      - --rf.device_args="tx_port=tcp://*:5564,rx_port=tcp://192.168.28.60:5565,id=ue2,base_srate=1.92e6"
