db_uri: mongodb://mongoadmin:secret@mongodb/open5gs?authSource=admin

logger:
  file: /usr/local/var/log/open5gs/open5gs.log
  trace:
    app: 1
    diameter: 1
    gtpv2: 1
    gtp: 1

parameter:
  no_ipv6: true

mme:
    freeDiameter:
      identity: mme.localdomain
      realm: localdomain
      listen_on: 192.168.26.20
      no_fwd: true
      load_extension:
        - module: /freeDiameter/dbg_msg_dumps.fdx
          conf: 0x8888
        - module: /freeDiameter/dict_rfc5777.fdx
        - module: /freeDiameter/dict_mip6i.fdx
        - module: /freeDiameter/dict_nasreq.fdx
        - module: /freeDiameter/dict_nas_mipv6.fdx
        - module: /freeDiameter/dict_dcca.fdx
        - module: /freeDiameter/dict_dcca_3gpp.fdx
      connect:
        - identity: hss.localdomain
          addr: 192.168.26.10

    s1ap:
      - addr: 192.168.26.20
    gtpc:
      - addr: 192.168.26.20
    gummei:
      plmn_id:
        mcc: 001
        mnc: 01
      mme_gid: 2
      mme_code: 1
    tai:
      plmn_id:
        mcc: 001
        mnc: 01
      tac: 1
    security:
        integrity_order : [ EIA2, EIA1, EIA0 ]
        ciphering_order : [ EEA0, EEA1, EEA2 ]

    network_name:
        full: Open5GS

sgwc:
    gtpc:
      - addr: 192.168.26.30
    pfcp:
      - addr: 192.168.26.30

smf:
    sbi:
      - addr: 192.168.26.40
        port: 7777
    pfcp:
      - addr: 192.168.26.40
    gtpc:
      - addr: 192.168.26.40
    gtpu:
      - addr: 192.168.26.40
    subnet:
      - addr: 10.10.0.1/16
        apn: internet
        dev: ogstap
      - addr: 10.11.0.1/16
        apn: internet2
        dev: ogstap2
      - addr: 10.12.0.1/16
        apn: iot.nb
        dev: ogstap3
      - addr: 10.50.0.1/16 # FALLBACK SUBNET
    dns:
      - 8.8.8.8
      - 8.8.4.4
    mtu: 1400
    freeDiameter:
      identity: smf.localdomain
      realm: localdomain
      listen_on: 192.168.26.40
      no_fwd: true
      load_extension:
        - module: /freeDiameter/dbg_msg_dumps.fdx
          conf: 0x8888
        - module: /freeDiameter/dict_rfc5777.fdx
        - module: /freeDiameter/dict_mip6i.fdx
        - module: /freeDiameter/dict_nasreq.fdx
        - module: /freeDiameter/dict_nas_mipv6.fdx
        - module: /freeDiameter/dict_dcca.fdx
        - module: /freeDiameter/dict_dcca_3gpp.fdx
      connect:
        - identity: pcrf.localdomain
          addr: 192.168.26.50
amf:
    sbi:
      - addr: 192.168.26.60
        port: 7777
    ngap:
      - addr: 192.168.26.60
    guami:
      - plmn_id:
          mcc: 001
          mnc: 01
        amf_id:
          region: 2
          set: 1
    tai:
      - plmn_id:
          mcc: 001
          mnc: 01
        tac: 1
    plmn_support:
      - plmn_id:
          mcc: 001
          mnc: 01
        s_nssai:
          - sst: 1
            sd: 000000
      - plmn_id:
          mcc: 001
          mnc: 01
        s_nssai:
          - sst: 1
            sd: 0xffffff
    security:
        integrity_order : [ NIA2, NIA1 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
    network_name:
        full: Open5GS
    amf_name: open5gs-amf0

sgwu:
    pfcp:
      - addr: 192.168.27.31
    gtpu:
      - addr: 192.168.27.31

upf:
    pfcp:
      - addr: 192.168.27.41
        apn: [internet, internet2, iot.nb]
    gtpu:
      - addr: 192.168.27.41
    subnet:
      - addr: 10.10.0.1/16
        apn: internet
        dev: ogstap
      - addr: 10.11.0.1/16
        apn: internet2
        dev: ogstap2
      - addr: 10.12.0.1/16
        apn: iot.nb
        dev: ogstap3
      - addr: 10.50.0.1/16 # FALLBACK SUBNET

hss:
    freeDiameter:
      identity: hss.localdomain
      realm: localdomain
      listen_on: 192.168.26.10
      no_fwd: true
      load_extension:
        - module: /freeDiameter/dbg_msg_dumps.fdx
          conf: 0x8888
        - module: /freeDiameter/dict_rfc5777.fdx
        - module: /freeDiameter/dict_mip6i.fdx
        - module: /freeDiameter/dict_nasreq.fdx
        - module: /freeDiameter/dict_nas_mipv6.fdx
        - module: /freeDiameter/dict_dcca.fdx
        - module: /freeDiameter/dict_dcca_3gpp.fdx
      connect:
        - identity: mme.localdomain
          addr: 192.168.26.20
pcrf:
    freeDiameter:
      identity: pcrf.localdomain
      realm: localdomain
      listen_on: 192.168.26.50
      no_fwd: true
      load_extension:
        - module: /freeDiameter/dbg_msg_dumps.fdx
          conf: 0x8888
        - module: /freeDiameter/dict_rfc5777.fdx
        - module: /freeDiameter/dict_mip6i.fdx
        - module: /freeDiameter/dict_nasreq.fdx
        - module: /freeDiameter/dict_nas_mipv6.fdx
        - module: /freeDiameter/dict_dcca.fdx
        - module: /freeDiameter/dict_dcca_3gpp.fdx
      connect:
        - identity: smf.localdomain
          addr: 192.168.26.40

nrf:
    sbi:
      - addr:
        - 192.168.26.61
        port: 7777

ausf:
    sbi:
      - addr: 192.168.26.70
        port: 7777

udm:
    sbi:
      - addr: 192.168.26.80
        port: 7777

pcf:
    sbi:
      - addr: 192.168.26.93
        port: 7777

nssf:
    sbi:
      - addr: 192.168.26.92
        port: 7777
    nsi:
      - addr: 192.168.26.61
        port: 7777
        s_nssai:
          sst: 1
          sd: 000000

bsf:
    sbi:
      - addr: 192.168.26.91
        port: 7777

udr:
    sbi:
      - addr: 192.168.26.90
        port: 7777
