# using version 2 for the gateway option with ipam
version: '2'

networks:
  cpn:
    external:
      name: cpn

services:
  webui:
    image: iqtlabs/open5gs:v0.7.3
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=dev
      - 'DB_URI=mongodb://${DB_USER}:${DB_PASS}@mongodb/open5gs?authSource=admin'
      - DB_HOST=mongodb
    container_name: webui
    hostname: webui
    ports:
      - "3000:3000"
    entrypoint:
      - npm
    command:
      - run
      - dev
      - --prefix
      - /open5gs/webui
    networks:
      cpn:
        ipv4_address: 192.168.26.6
    labels:
      - "dovesnap.faucet.mirror=true"
      - "daedalus.namespace=primary"
