---
# using version 2 for the gateway option with ipam
version: '2'

networks:
  upn:
    external:
      name: upn

services:
  sgwu:
    image: open5gs:latest
    container_name: sgwu
    hostname: sgwu
    command:
      - "/scripts/run_sgwu.sh"
    volumes:
      - "../configs:/usr/local/etc:z"
    networks:
      upn:
        ipv4_address: 192.168.27.31
    labels:
      - "dovesnap.faucet.mirror=true"
      - "daedalus.namespace=primary"
  sgwu2:
    image: open5gs:latest
    container_name: sgwu2
    hostname: sgwu2
    command:
      - "/scripts/run_sgwu.sh"
    volumes:
      - "../configs:/usr/local/etc:z"
    networks:
      upn:
        ipv4_address: 192.168.27.32
    labels:
      - "dovesnap.faucet.mirror=true"
      - "daedalus.namespace=primary"
  upf:
    image: open5gs:latest
    container_name: upf
    hostname: upf
    command:
      - "/scripts/run_upf.sh"
      - "10.10.0.1/16"
    volumes:
      - "../configs:/usr/local/etc:z"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.conf.all.send_redirects=0
      - net.ipv4.conf.default.send_redirects=0
    networks:
      upn:
        ipv4_address: 192.168.27.41
    labels:
      - "dovesnap.faucet.mirror=true"
      - "daedalus.namespace=primary"
  upf2:
    image: open5gs:latest
    container_name: upf2
    hostname: upf2
    command:
      - "/scripts/run_upf.sh"
      - "10.11.0.1/16"
      - "10.12.0.1/16"
    volumes:
      - "../configs:/usr/local/etc:z"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.conf.all.send_redirects=0
      - net.ipv4.conf.default.send_redirects=0
    networks:
      upn:
        ipv4_address: 192.168.27.42
    labels:
      - "dovesnap.faucet.mirror=true"
      - "daedalus.namespace=primary"
