# using version 2 for the gateway option with ipam
version: '2'

networks:
  ran:
    external:
      name: ran
services:
  limesdr-enb:
    image: iqtlabs/srsran-lime:v0.8.1
    container_name: limesdr-enb
    cap_add:
      - SYS_NICE
      - SYS_RAWIO
    networks:
      ran:
        ipv4_address: 192.168.29.63
    volumes:
      - "../configs/srsRAN/limesdr:/config:z"
    entrypoint:
      - srsenb
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    labels:
      - "daedalus.namespace=primary"
    command:
      - /config/enb.conf
      - --enb.name=limesdr-ENB01
      - --enb.n_prb=${LIMESDR_PRB}
      - --enb.tac=1
      - --enb.mcc=001
      - --enb.mnc=01
      - --enb.enb_id=0x63
      - --enb.mme_addr=192.168.26.20
      - --enb.gtp_bind_addr=192.168.29.63
      - --enb.s1c_bind_addr=192.168.29.63
      - --rf.device_name=soapy
      - --rf.device_args=auto
      - --rf.dl_earfcn=${LIMESDR_EARFCN}
      - --rf.tx_gain=${LIMESDR_TXGAIN}
      - --rf.rx_gain=${LIMESDR_RXGAIN}
