name: buildx-srsran

on:
  push:
    branches: main
    tags: 'v*'

jobs:
  srsran:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      with:
        fetch-depth: 0
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Change for main
      id: change_version
      run: if [ "${{ steps.get_version.outputs.VERSION }}" == "main" ]; then echo ::set-output name=VERSION::latest; else echo ::set-output name=VERSION::${{ steps.get_version.outputs.VERSION }}; fi
    - name: Set up qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      if: github.repository == 'iqtlabs/daedalus' && github.event_name == 'push'
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: blue/5G/daedalus/5G/srsRAN
        platforms: linux/amd64,linux/arm64
        push: true
        tags: iqtlabs/srsran:${{ steps.change_version.outputs.VERSION }}
      if: github.repository == 'iqtlabs/daedalus' && github.event_name == 'push'
