name: release

on:
  push:
    branches: main
    tags: 'v*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      with:
        fetch-depth: 0
    - name: Build core package
      id: build_core_package
      run: |
        sudo apt-get update && \
        sudo apt-get install -yq --no-install-recommends python3-pip python3-dev python3-setuptools && \
        pip3 install wheel build && \
        cd blue && python3 -m build --sdist --wheel
      if: github.repository == 'iqtlabs/daedalus' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    - name: Publish package
      if: github.repository == 'iqtlabs/daedalus' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_TOKEN }}
        packages_dir: blue/dist
