name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: shell_test
      run: |
        wget "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" && \
        tar --xz -xvf "shellcheck-stable.linux.x86_64.tar.xz" && \
        shellcheck() { "shellcheck-stable/shellcheck" "$@"; } && \
        shellcheck --version && \
        /bin/bash --version && \
        for shellscript in $(find . -type f -name "*.sh"); do /bin/bash -n "$shellscript" && shellcheck -x -e SC2069 -e SC2048 "$shellscript"; done
    - name: unit_test
      run: |
        ./blue/tests/install_test.sh && \
        pip3 install codecov && \
        PATH=/home/runner/.local/bin:$PATH py.test -v -vv --cov-report term-missing --cov=blue/5G/daedalus -c .coveragerc && \
        PATH=/home/runner/.local/bin:$PATH coverage report && \
        PATH=/home/runner/.local/bin:$PATH coverage xml
  srsran_enb_ue_int_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: srsran_enb_ue_int_test
        run: |
          ./blue/tests/install_test.sh && ./blue/tests/test_srsran_enb_ue.sh
