name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        fetch-depth: 0
    - name: shell_test
      run: |
        wget "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" && \
        tar --xz -xvf "shellcheck-stable.linux.x86_64.tar.xz" && \
        shellcheck() { "shellcheck-stable/shellcheck" "$@"; } && \
        shellcheck --version && \
        /bin/bash --version && \
        for shellscript in $(find blue -type f -name "*.sh"); do /bin/bash -n "$shellscript" && shellcheck -x -e SC2069 -e SC2048 "$shellscript"; done
    - name: code_check
      run: |
        ./blue/tests/install_test.sh && \
        export PYTHONPATH=$PWD/blue/5G:$PYTHONPATH && \
        timeout 900 pytype . --exclude=blue/build && \
        pylint --fail-under=6.0 --disable=expression-not-assigned blue
    - name: unit_test_create_remove_networks
      run: |
        PATH=/home/runner/.local/bin:$PATH timeout 900 py.test -vvv -k "create_remove_networks" --capture=tee-sys --cov-report term-missing --cov=blue/5G/daedalus -c .coveragerc
    - name: unit_test_no_build_no_create_remove_networks
      run: |
        PATH=/home/runner/.local/bin:$PATH timeout 900 py.test -vvv -k "not build and not create_remove_networks " --cov-append --capture=tee-sys --cov-report term-missing --cov=blue/5G/daedalus -c .coveragerc
    - name: unit_test_build
      run: |
        PATH=/home/runner/.local/bin:$PATH timeout 7200 py.test -vvv -k "build" --cov-append --capture=tee-sys --cov-report term-missing --cov=blue/5G/daedalus -c .coveragerc && \
        PATH=/home/runner/.local/bin:$PATH coverage report && \
        PATH=/home/runner/.local/bin:$PATH coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.4
      if: github.repository == 'iqtlabs/daedalus'
  integration_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: setup_int_tests
        run: |
          ./blue/tests/install_test.sh && \
          cd blue && sudo python3 setup.py install && cd ..
      - name: srsran_enb_ue_int_test
        run: |
          ./blue/tests/test_setup.sh && \
          ./blue/tests/test_srsran_enb_ue.sh
      - name: ueransim_gnb_ue_int_test
        run: |
          ./blue/tests/test_setup.sh && \
          ./blue/tests/test_ueransim_gnb_ue.sh
